import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:3000/');
  await page.getByRole('button', { name: '✨ Sign In' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('bobsmith@gmail.com');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('TestPass456!');
  await page.getByRole('button', { name: '✨ Sign In & Explore' }).click();
  await page.getByRole('button', { name: 'Create Group' }).click();
  await page.getByRole('textbox', { name: 'Enter group title...' }).click();
  await page.getByRole('textbox', { name: 'Enter group title...' }).fill('test A');
  await page.getByRole('textbox', { name: 'Describe your travel group' }).click();
  await page.getByRole('textbox', { name: 'Describe your travel group' }).fill('this is test group a');
  await page.getByRole('textbox', { name: 'Where are you planning to go?' }).click();
  await page.getByRole('textbox', { name: 'Where are you planning to go?' }).fill('nonthaburi');
  await page.getByRole('textbox').nth(3).fill('2025-11-09');
  await page.getByRole('textbox').nth(4).fill('2025-11-16');
  await page.getByRole('button', { name: '🏖️ Sea & Beach' }).click();
  await page.getByRole('button', { name: '⛰️ Mountain & Hills' }).click();
  await page.getByRole('button', { name: '⛰️ Mountain & Hills' }).click();
  await page.getByRole('button', { name: '💧 Waterfalls' }).click();
  await page.getByRole('button', { name: '⛰️ Mountain & Hills' }).click();
  await page.getByRole('button', { name: '🛍️ Shopping Malls' }).click();
  await page.getByRole('button', { name: '🏪 Local Markets' }).click();
  await page.getByRole('button', { name: '☕ Cafes & Coffee' }).click();
  await page.getByRole('button', { name: '🎉 Festivals & Events' }).click();
  await page.getByRole('button', { name: '🏛️ Museums & Galleries' }).click();
  await page.getByRole('button', { name: '🍴 Food Streets' }).click();
  await page.getByRole('button', { name: 'Continue to Itineraries' }).click();
  await page.getByRole('button', { name: 'New Itinerary' }).click();
  await page.getByRole('textbox', { name: 'Title' }).click();
  await page.getByRole('textbox', { name: 'Title' }).fill('pump');
  await page.getByRole('textbox', { name: 'Start Date' }).fill('2025-11-12');
  await page.getByRole('textbox', { name: 'End Date' }).fill('2025-11-13');
  await page.getByRole('button', { name: 'Create Itinerary' }).click();
  await page.getByRole('button', { name: 'New Itinerary' }).click();
  await page.getByRole('textbox', { name: 'Title' }).click();
  await page.getByRole('textbox', { name: 'Title' }).fill('pump b');
  await page.getByRole('textbox', { name: 'Start Date' }).fill('2025-11-15');
  await page.getByRole('textbox', { name: 'End Date' }).fill('2025-11-16');
  await page.getByRole('button', { name: 'Create Itinerary' }).click();
  await page.getByRole('button', { name: 'Complete Group Setup' }).click();
});
